spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/students}
      username: ${SPRING_DATASOURCE_USERNAME:root}
      password: ${SPRING_DATASOURCE_PASSWORD:root}

jwt:
  expiration: 604800
  header: 'Authorization'
  secret: 'super_secret_key_yes'

#logging:
#  level:
#    org:
#      springframework: DEBUG
