spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

jwt:
  expiration: 604800
  header: 'Authorization'
  secret: 'super_secret_key_yes'

#logging:
#  level:
#    org:
#      springframework: DEBUG
