spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
      username: ${JDBC_DATABASE_USERNAME}
      password: ${JDBC_DATABASE_PASSWORD}

jwt:
  expiration: 604800
  header: 'Authorization'
  secret: 'super_secret_key_yes'

#logging:
#  level:
#    org:
#      springframework: DEBUG
